import pygame
import os
import sys
sys.path.append("../")
sys.path.append("../pygame_general_functions")
sys.path.append("../../Assets")
from pygconstants import PYGConstants
P = PYGConstants()
REG_FONT = pygame.font.SysFont("comicsans", 25)
WIN = pygame.display.set_mode((P.WIDTH, P.HEIGHT))
pygame.display.set_caption("RPG")
#images used
WAVE1 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave1.png')
WAVE2 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave2.png')
WAVE3 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave3.png')
WAVE4 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave4.png')
WAVE5 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave5.png')
WAVE6 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave6.png')
WAVE7 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave7.png')
WAVE8 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave8.png')
WAVE9 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave9.png')
WAVE10 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave10.png')
WAVE11 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave11.png')
WAVE12 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave12.png')
WAVE13 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave13.png')
WAVE14 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave14.png')
WAVE15 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave15.png')
WAVE16 = pygame.image.load(r'C:\Users\draco\Documents\RPG\pygameRPG\Assets\wave16.png')
#function that draws a wave
def enemy_wave_attack():
	width, height = WIN.get_size()
	WAVE_IMG = pygame.transform.scale(WAVE1, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE2, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE3, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE4, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE5, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE6, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE7, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE8, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE9, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE10, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE11, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE12, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE13, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE14, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE15, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE16, (width//2, height//1.5))
	WIN.blit(WAVE_IMG, (width//2, height//6))
	pygame.display.update()
	pygame.time.delay(50)

def hero_wave_attack():
	width, height = WIN.get_size()
	WAVE_IMG = pygame.transform.scale(WAVE1, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE2, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE3, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE4, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE5, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE6, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE7, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE8, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE9, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE10, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE11, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE12, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE13, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE14, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE15, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)
	WAVE_IMG = pygame.transform.scale(WAVE16, (width//2, height//1.5))
	WAVE_IMG = pygame.transform.flip(WAVE_IMG, True, False)
	WIN.blit(WAVE_IMG, (0, height//6))
	pygame.display.update()
	pygame.time.delay(50)

hero_wave_attack()
pygame.quit()
